// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/helix_js_version.test.ts.

/** The version of the `@tssuite/helix-js` package. */
export const helixJsVersion = '0.3.0';
